name: "Kubernetes Deploy Action"
description: "Updates Kubernetes resources with YTT templating."
branding:
  icon: "anchor"
  color: "blue"
inputs:
  template_dir:
    description: "Location of YTT templates or Kubernetes yaml"
    required: true
  template_values:
    description: "YAML string of data values to set in the templates"
    required: false
  await_rollout_for_deployment:
    description: "Deployment name to await a successful rollout status"
    required: false
outputs:
  result:
    description: "Output of the kubectl command run"
runs:
  using: "docker"
  image: "docker://danforys/k8s-deploy-action:ytt-templating"
