name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Build
        run: >
            docker build .
            --tag danforys/k8s-deploy-action:${GITHUB_SHA:0:7}
            --tag danforys/k8s-deploy-action:latest
      - name: Docker Hub Login
        run: docker login --username danforys --password ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Push
        run: |
          docker push danforys/k8s-deploy-action:${GITHUB_SHA:0:7}
          docker push danforys/k8s-deploy-action:latest